name: Setup

description: Setup

inputs:
  node_version:
    description: Node.js version
    required: false
    default: "16"

runs:
  using: composite
  steps:
    - name: Checkout all commits
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set NX SHAs
      uses: nrwl/nx-set-shas@v2
      with:
        main-branch-name: "master"
    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node_version }}
        registry-url: https://registry.npmjs.org
    - name: Install
      shell: bash
      run: npm install
