name: Main
on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [16]
    defaults:
      run:
        working-directory: ./app
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        uses: ./.github/actions/setup
        with:
          node_version: ${{ matrix.node_version }}
      - name: Test
        uses: ./.github/actions/test
      # TODO: set up release process
      # - name: Release
      #   uses: ./.github/actions/release
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
