name: Main
on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        go-version: [ '1.16', '1.17' ]
        node_version: [16]
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        uses: ./.github/actions/setup
        with:
          node_version: ${{ matrix.node_version }}
          go-version: ${{ matrix.go-version }}
      - name: Test
        uses: ./.github/actions/test
  # TODO: set up release process
  release:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ darwin, linux, windows ]
        arch: [ arm64, amd64 ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        uses: ./.github/actions/setup
        with:
          node_version: 16
          go-version: 1.17
      - name: Build web
        shell: bash
        run: npx nx build
        working-directory: ./app
      - name: Build ${{ matrix.os }}/${{ matrix.arch }}
        shell: bash
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: go build -o dist/ .
      - name: Save artifacts
        uses: actions/upload-artifact@v2
        with:
          name: embarcadero-${{ matrix.os }}-${{ matrix.arch }}
          path: dist/*
          retention-days: 30
