name: PR
on:
  pull_request:

jobs:
  pr:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        go-version: [ '1.16', '1.17' ]
        node_version: [16]
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        uses: ./.github/actions/setup
        with:
          node_version: ${{ matrix.node_version }}
          go-version: ${{ matrix.go-version }}
      - name: Test
        uses: ./.github/actions/test
